### PR TITLE
some additions

### PR DESCRIPTION
**Pull request by Vilot122**
This covers almost everything from the old PR. Please review and see if everything looks alright for merging

### CODE REVIEW

**Comment by Vilot122** [comment]
I don't see a way to open an issue, but I noticed two issues in the repo that I don't know how to do:

toontown_map_old in the repo looks like it was only upscaled (not cleaned) and given the final alpha channel. The 2003 phase files has an alpha for this variant and a blurred version of the same texture
This was the source: https://x.com/jesseschell/status/708458818158661632

tt_t_ara_TT_streetlight_halloween_bowtie looks like it was shortened when light was added to it. In the future, it should be the same size as the source:
https://github.com/toontownretro/ttmodels/blob/frizzy-things/raw/tt_t_ara_TT_streetlight_halloween_bowtie.png

**Comment by Bob-by** [comment]
Thanks for another commit looks good to me but I checked the popcorn cart model changing the the texture to yours causes the text to be flipped on 1 side, in the past I hand-edited it to fix the grammar mistake but I don't remember if I changed the rotation of the other one.

For the original version of the map I took the texture from the Twitter post and downscaled the asset trunk one and applied its alpha textures while slightly moving the texture so it matches with the posing of the final one. I no longer have access to the program I used to remove JPEG artifacts so I pushed it as is.

Are you referring to the version exclusive to the branch, that one is not used for building only testing and is probably now outdated with yesterdays commits (the main branch one should have it fixed).

**Comment by Vilot122** [comment]
I'm all ears to how we can properly layer the popcorn cart texture, or we could simply keep the original texture seperately in the repo. Having both would be ideal.

There are two main versions of the toontown map, the one on twitter (beta) and the final one. There are also blurred variants found in phase files from 2003-2008, each with their own alpha file. We can focus on the main ones.
In the repo, the beta toontown map is using the alpha channel of the final map. In the 2001 phase files, it had its own alpha file. It looks like we can take the map directly from twitter and resize the 2001 alpha file to match it and it should look better and be more accurate.

And that old repo was where I found all the old halloween textures. It looks like the streetlight found in the main repo was squished down a tad compared to the source texture I linked. We're losing some information, so ideally the streetlight should be unaltered, but with the glow from the final.

I made a commit addressing the first issue, but i don't know how to fix the latter two. Let me know your opinion

**Comment by Bob-by** [comment]
I'd rather keep the edited one as the default one but I'm open to bringing back the original texture under its typo name popcron_cart.tif

I believe I intentionally didn't do much with the wip maps because all of them shared 1 mistake that was never fixed. The 2003 map that had all of its canceled content removed also had additional editing done to fix the consistency but when they began adding new parts for some reason they used the original map and blurred out all the zones and didn't bring over the added changes making the map look very inconsistent like how it is nowadays (for example Acorn Acres being surrounded by a red color left by construction zone). If you have any thoughts on this one let me know.

Not 100% sure about the halloween streetlight but I used the final version resized to 512x251 and applied the higher res on top of it so I could get the light glow back and I think that had caused issues with the main pole being cropped in the final version.

**Comment by Vilot122** [comment]
popcron cart is a great idea, I pushed this.

I misremembered the situation in my first comment. We don't need to focus on the blurred maps, it's up to you whether those get added or not. I don't know how to merge the 2001 alpha file and the twitter map together. I don't have access to photoshop either, so I don't know what my options are. In the end, we should have a png/tif file that has 680x589 pixels.

I made my own version of the streetlight, unsquashed from the original, and overlayed the spotify texture underneath. I scaled the spotify layer to match the original, and the lights look like they match up perfectly. Only issue is two layers of transparency darken each other. I cropped the spotify texture up until the first light pixel I found. It's impossible to do this perfectly, but this is better than the one in the repo. A smaller issue I had was converting the image to tif and preserving the original metadata, I still don't know how to do this.

I appreciate your advice.

**Comment by Bob-by** [comment]
Thanks for your streetlight version!

This is the 2001 1.0.5 map jpg with added rgb alpha channel both are 256x256
toontown_map

This is the map posted on Twitter with the rgb channel from 2001 rescaled to 708x613 (708x613 should be the highest available size of the version posted vs 1071x929 in maps/)
toontown_map_old_1

Using the 2001 alpha channel definitely makes it closer to the original version but I'm unsure about the sudden edge crops that are only present in 2001 and not the final version, but it also looks like the alpha channel was altered during the updates.

Let me know if you think mixing the Twitter image with the 2001 alpha channel would be appropriate or if there is a better way to follow

**Comment by Vilot122** [comment]
Out of curiosity, where did the higher resolution map come from? On examining, it looks like it's just an upscale of the twitter one. I tested the beta map in game and you can hardly notice the cut off, so it's better to attach the 2001 alpha. The final one obscures a lot of the image.

**Comment by Bob-by** [comment]
I downloaded it as is from Twitter and that were the dimensions used I didn't modify it at all except adding the 2001 alpha channel
All right, I'll replace it with the new one in my next commit that should should be out either today or tomorrow

**Comment by Bob-by** [comment]
Gonna merge this now and then add some of my changes on top of it. Thanks for your contribution!

**Pull request merged**
